name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: ['4.0', '3.3', '3.2', '2.7']

    steps:
    - name: "☁️ checkout repository"
      uses: actions/checkout@v7
      with:
        submodules: true

    - name: "📦 install dependencies"
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: "📀 building"
      run: bundle exec rake transform:icons

    - name: "🔍 run tests"
      run: bundle exec rake
