name: Release

on:
  release:
    types: [published]

jobs:
  test:
    uses: ./.github/workflows/ci.yml

  publish:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
    - name: "☁️ checkout repository"
      uses: actions/checkout@v7
      with:
        submodules: true

    - name: "📦 install dependencies"
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '4.0'
        bundler-cache: true

    - name: "📀 building"
      run: bundle exec rake transform:icons

    - uses: rubygems/release-gem@v1
